### ISSUE TITLE
Uncaught TypeError: deepmerge is not a function

### ISSUE THREAD

**Issue by royalharsh** [perry-mitchell/webdav-client#77]
Recently, I was trying to use this library to connect to an owncloud instance. But, this doesn't seem to work. I am getting the following error:

```
Uncaught TypeError: deepmerge is not a function
    at Object.getDirectoryContents (factory.js?879e:118)
    at Object.eval (main.js?1c90:40)
    at eval (80:45)
    at Object.<anonymous> (app.js:1240)
    at __webpack_require__ (app.js:679)
    at fn (app.js:89)
    at Object.<anonymous> (app.js:1104)
    at __webpack_require__ (app.js:679)
    at app.js:725
    at app.js:728
```
I did `npm install deepmerge`. But, it didn't help. @perry-mitchell?

**Comment by perry-mitchell** [comment]
That's weird, because we have [tests for `getDirectoryContents`](https://github.com/perry-mitchell/webdav-client/blob/master/test/specs/getDirectoryContents.spec.js#L20). What version of `webdav` do you have installed?

You could try destroying `node_modules` and running `npm cache clear --force` before running `npm i` again..

**Comment by royalharsh** [comment]
Right now, I'm using `webdav: 1.2.0`

**Comment by perry-mitchell** [comment]
Ok.. well I can’t currently see how you could get that error. Can you share some code that uses it? Are you using webpack?

**Comment by royalharsh** [comment]
Yes, I'm using webpack.

**Comment by perry-mitchell** [comment]
Is this an open source project I could look at? Deepmerge’s version was updated in the last release, but I wouldn’t think that this could cause any new issues. I would guess that this is most likely a configuration issue with webpack.

**Comment by royalharsh** [comment]
Here you go: https://github.com/royalharsh/petabyte

**Comment by perry-mitchell** [comment]
Thanks @royalharsh - Unfortunately I wasn't able to build the project due to several eslint errors, but I also couldn't see any issues with what you've set up. It may be that `deepmerge` cannot be resolved in node_modules. I would recommend **not** having it in your `package.json` at all, as you don't use it, it should be installed by webdav and used by it when needed. If your built copy doesn't resolve deepmerge, it's most likely a webpack configuration issue. I'll be updating it in my webpack projects soon and I'll report back if I find something.

That being said, I'll most likely have to close this issue (after I've checked of course), as webpack is not the primary target for this library. It's built for node and I don't particularly want to have to support webpack officially as every webpack config is different.

There's nothing special about the deepmerge dependency in this library, so it should be resolved as expected.

**Comment by royalharsh** [comment]
Ok, no worries.

**Comment by subdavis** [comment]
I can reproduce `deepmerge is not a function` since the upgrade to 1.2.0.  

Reverted to the previous release and the issue disappeared.  As you say, there's nothing special about the deepmerge dependency, and I thought I was losing my mind until I saw @royalharsh open this issue.

**Comment by perry-mitchell** [comment]
@royalharsh @subdavis After experimenting a bit, I can confirm that this is indeed not a webpack configuration issue as I originally suspected. I'm also seeing the error and have opened an issue: KyleAMathews/deepmerge#97.

I would suggest using 1.1.2 for the time being until this is resolved. If it looks like it'll take too long I'll remove the deepmerge dependency.

**Comment by perry-mitchell** [comment]
I might consider changing to the [merge](https://www.npmjs.com/package/merge) module as it looks to be a bit more on the popular side.

**Comment by perry-mitchell** [comment]
Ok, so it seems that `deepmerge` will not be fixing their repo for webpack users, which is disappointing. I'll switch to using `merge` immediately.

**Comment by perry-mitchell** [comment]
1.2.1 has the downgraded deepmerge version. Could you confirm that this works for you @royalharsh @subdavis ?

**Comment by subdavis** [comment]
Confirmed working!   Thanks for taking care of this :+1:
